### ISSUE TITLE
Resize Not Consistent Across Themes

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/gdrive#20]
A better solution for this: https://github.com/hwdsbcommons/gdrive/issues/19
 is to resize the iframe. This leaves access to the iFrame Pop Out option, without overwhelming the page. The resize doesn't seem to work consistently across themes though. I recognize this is probably a shortcoming of the theme, but wondered if we might be able to force our sizing a bit more robustly. 

Here, in the Wilson theme, you can see the icon, having been resized to 50x50, is still rendering at 600+px

![2017-03-02_10-29-30](https://cloud.githubusercontent.com/assets/480667/23513846/81928f5a-ff33-11e6-8a99-25ceee5db586.png)

You can see this in action at https://sand.commons.hwdsb.on.ca/2017/03/02/154/

In Twenty Twelve it works great: 

![2017-03-02_10-35-21](https://cloud.githubusercontent.com/assets/480667/23514012/fbc8db94-ff33-11e6-9cc8-79b642928d84.png)

That you can find here: https://sandbox.commons.hwdsb.on.ca/external-media/

**Comment by r-a-y** [comment]
Wilson is special because it uses JS to resize all iframes, so it's not really possible to do this.

**Comment by mrjarbenne** [comment]
Ok. What about a toggle to either show or disable the iframe, in cases where it's not a supported format? I don't want to disable it entirely by design, because the pop out makes sense in some contexts. Then it would just be a download link.

**Comment by r-a-y** [comment]
It's not possible to determine if a file stored in Google Drive is a supported format or not based solely on the URL, which is what Google Docs Shortcode uses.

However, we can take some guesses with GDrive because we have access to the mime type, but this still wouldn't be 100% entirely accurate.  Using the mime type as a check, I can probably add in a `disable-iframe` or `hide` attribute to Google Docs Shortcode, which will not render the iframe.  How does that sound?

**Comment by mrjarbenne** [comment]
That sounds perfect. Sorry if it seems counter-productive to have a shortcode that adds the doc, with an option not to add the doc.

**Comment by r-a-y** [comment]
K, going to close this one in favor of #19.
